import{a as u,i as m}from"./assets/vendor-96017409.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();u.defaults.headers.common["x-api-key"]="live_4cGo7pfpOk2mCrYNuFxrzN4x9Tr8FpKtStGbwBmJipn0B1TW87rAnmh8GPepxKDN";function p(){return u.get("https://api.thecatapi.com/v1/breeds").then(s=>s.data.map(t=>({name:t.name,id:t.id})))}function f(s){return u.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${s}`).then(t=>{if(!t.data.length)throw new Error("Chosen breed doesn't exist!");const{url:o,breeds:n}=t.data[0];return{url:o,description:n[0].description,name:n[0].name,temperament:n[0].temperament}})}m.settings({position:"topRight"});const c=document.querySelector(".breed-select"),d=document.querySelector(".loader"),l=document.querySelector(".error"),a=document.querySelector(".cat-info");c.addEventListener("input",h);p().then(s=>{c.innerHTML=s.map(t=>`<option value="${t.id}">${t.name}</option>`).join(""),c.classList.remove("hidden")}).catch(s=>{m.error({message:s.message}),l.classList.remove("hidden")}).finally(()=>{d.classList.add("hidden")});function h(s){const t=s.target.value;d.classList.remove("hidden"),f(t).then(({url:o,description:n,name:e,temperament:r})=>{a.innerHTML=`
        <img src="${o}" alt="a cat of ${e} breed" width="500px" />
        <div class="textblock">
            <h1 class="title">${e}</h1>
            <p class="text">${n}</p>
            <p class="text"><span class="bold">Temperament: </span>${r}</p>
        </div>
      `,a.classList.remove("hidden"),l.classList.add("hidden")}).catch(o=>{m.error({message:o.message}),a.classList.add("hidden"),l.classList.remove("hidden")}).finally(()=>{d.classList.add("hidden")})}
//# sourceMappingURL=commonHelpers.js.map
